/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface NacosConfigResponse {
  /** Namespace/Tenant */
  namespace: string
  /** DataId */
  dataId: string
  /** Group */
  group: string
  /** Content */
  content: string
  /** Content's Type; e.g. json,properties,xml,html,text,yaml */
  contentType: string
  /** Content's md5 */
  md5: string
}
export class NacosConfigClient {
  constructor(serverAddr: string, namespace: string, appName: string, username?: string | undefined | null, password?: string | undefined | null)
  getConfig(dataId: string, group: string): string
  addListener(dataId: string, group: string, listener: (err: Error | null, value: NacosConfigResponse) => any): void
}
