/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface ClientOptions {
  /** Server Addr, e.g. address:port[,address:port],...] */
  serverAddr: string
  /** Namespace/Tenant */
  namespace: string
  /** AppName */
  appName?: string
  /** Username for Auth */
  username?: string
  /** Password for Auth */
  password?: string
}
export interface NacosConfigResponse {
  /** Namespace/Tenant */
  namespace: string
  /** DataId */
  dataId: string
  /** Group */
  group: string
  /** Content */
  content: string
  /** Content's Type; e.g. json,properties,xml,html,text,yaml */
  contentType: string
  /** Content's md5 */
  md5: string
}
/** Client api of Nacos Config. */
export class NacosConfigClient {
  constructor(clientOptions: ClientOptions)
  /** Get config's content. */
  getConfig(dataId: string, group: string): string
  /** Get NacosConfigResponse. */
  getConfigResp(dataId: string, group: string): NacosConfigResponse
  /** Publish config. */
  publishConfig(dataId: string, group: string, content: string): boolean
  /** Remove config. */
  removeConfig(dataId: string, group: string): boolean
  /** Add NacosConfigChangeListener callback func, which listen the config change. */
  addListener(dataId: string, group: string, listener: (err: Error | null, value: NacosConfigResponse) => any): void
}
